### ISSUE TITLE
Support bullet lists starting with * or +

### ISSUE THREAD

**Issue by damienrambout** [xing/XNGMarkdownParser#4]
Official Markdown documentation states that bullet lists can be started by `-`, `*` or `+`.
http://daringfireball.net/projects/markdown/syntax#list

I think it simply consists in updating the grammar and I would do it, but I believe it is hardcoded in your `XNGMarkdownTokenized.m` file.

Cheers.

**Comment by pietbrauer** [comment]
You could make a Pull Request, though?

**Comment by gskbyte** [comment]
Hi, 

it's not hardcoded into the ``XNGMarkdownTokenized.m`` file, because it's automatically generated by flex. To add a rule to the grammar, just edit https://github.com/xing/XNGMarkdownParser/blob/master/grammar/markdown.grammar. We would include into the project if you make a PR that implements it and passes all tests (including the needed new ones). Thanks!
